const ready = window.reaperAdmin
  ? Promise.resolve(window.reaperAdmin)
  : new Promise((resolve) => document.addEventListener('reaper:admin-ready', (event) => resolve(event.detail), { once: true }));
let context, clients=[], cases=[], templates=[];
const el=(id)=>document.getElementById(id);
const fmt=(v)=>v?new Date(v).toLocaleString():'—';
const hash=async(text)=>Array.from(new Uint8Array(await crypto.subtle.digest('SHA-256',new TextEncoder().encode(text))),(b)=>b.toString(16).padStart(2,'0')).join('');
function options(select,rows,label,first='Select'){select.innerHTML=`<option value="">${first}</option>`;for(const row of rows){const o=document.createElement('option');o.value=row.id;o.textContent=label(row);select.appendChild(o);}}
function render(container,headers,rows){container.replaceChildren();if(!rows.length){container.textContent='No records yet.';return;}const t=document.createElement('table');t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${h.label}</th>`).join('')}</tr></thead>`;const b=document.createElement('tbody');for(const r of rows){const tr=document.createElement('tr');for(const h of headers){const td=document.createElement('td');td.textContent=(h.render?h.render(r):r[h.key])??'—';tr.appendChild(td);}b.appendChild(tr);}t.appendChild(b);container.appendChild(t);}
async function loadRefs(){const {supabase}=context;const [cl,ca,tp]=await Promise.all([supabase.from('clients').select('id,full_name,email,state').order('full_name'),supabase.from('cases').select('id,client_id,case_type,title,status').order('created_at',{ascending:false}),supabase.from('agreement_templates').select('id,name,service_type,jurisdiction,version,title,active,legal_approved_at,legal_approved_by,created_at').order('created_at',{ascending:false})]);if(cl.error||ca.error||tp.error)throw cl.error||ca.error||tp.error;clients=cl.data||[];cases=ca.data||[];templates=tp.data||[];options(el('agreement-client'),clients,c=>`${c.full_name||c.email} (${c.email})`);options(el('agreement-template'),templates,t=>`${t.name} v${t.version} · ${t.jurisdiction||'all'} · ${t.legal_approved_at?'approved':'NOT APPROVED'}`);}
function wireCaseSelect(){el('agreement-client').addEventListener('change',()=>options(el('agreement-case'),cases.filter(c=>c.client_id===el('agreement-client').value),c=>c.title||c.case_type,'Select case'));}
async function loadLists(){const {supabase}=context;const [tp,ag]=await Promise.all([supabase.from('agreement_templates').select('id,name,service_type,jurisdiction,version,title,active,legal_approved_at,legal_approved_by,created_at').order('created_at',{ascending:false}),supabase.from('service_agreements').select('id,client_id,case_id,template_id,title,status,sent_at,accepted_at,declined_at,accepted_name,created_at').order('created_at',{ascending:false})]);templates=tp.data||[];render(el('templates-list'),[{label:'Template',render:r=>`${r.name} v${r.version}`},{label:'Service',key:'service_type'},{label:'Jurisdiction',render:r=>r.jurisdiction||'All'},{label:'Active',render:r=>r.active?'Yes':'No'},{label:'Legal approval',render:r=>r.legal_approved_at?`${fmt(r.legal_approved_at)} · ${r.legal_approved_by||'recorded'}`:'Required before sending'}],templates);render(el('agreements-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Agreement',key:'title'},{label:'Status',key:'status'},{label:'Sent',render:r=>fmt(r.sent_at)},{label:'Accepted',render:r=>fmt(r.accepted_at)},{label:'Accepted name',key:'accepted_name'}],ag.data||[]);options(el('agreement-template'),templates,t=>`${t.name} v${t.version} · ${t.jurisdiction||'all'} · ${t.legal_approved_at?'approved':'NOT APPROVED'}`);}
el('template-form').addEventListener('submit',async(e)=>{e.preventDefault();const body=el('template-body').value.trim();const payload={name:el('template-name').value.trim(),service_type:el('template-service').value.trim(),jurisdiction:el('template-jurisdiction').value.trim().toUpperCase()||null,version:Number(el('template-version').value),title:el('template-title').value.trim(),body,content_hash:await hash(body),active:false,legal_approved_at:null,legal_approved_by:null,created_by:context.profile.id};const {error}=await context.supabase.from('agreement_templates').insert(payload);el('template-status').textContent=error?'Draft template could not be saved.':'Unapproved draft template saved. It cannot be sent until legal approval is recorded.';if(!error){e.target.reset();el('template-version').value='1';await loadRefs();await loadLists();}});
el('agreement-form').addEventListener('submit',async(e)=>{e.preventDefault();const template=templates.find(t=>t.id===el('agreement-template').value);if(!template)return;const clientId=el('agreement-client').value,caseId=el('agreement-case').value,state=el('agreement-state').value;const {error}=await context.supabase.from('service_agreements').insert({client_id:clientId,case_id:caseId,template_id:template.id,title:template.title,body_snapshot:'pending trigger snapshot',content_hash:'pending',status:state,created_by:context.profile.id});if(error){console.error('Agreement creation failed',error);el('agreement-status').textContent=String(error.message||'').includes('legally_approved')?'Agreement blocked: this exact template/version is not legally approved for sending.':'Agreement could not be created.';}else{el('agreement-status').textContent=state==='sent'?'Agreement sent to client.':'Draft client agreement created.';e.target.reset();await loadLists();}});
wireCaseSelect();ready.then(async(v)=>{context=v;await loadRefs();await loadLists();}).catch(err=>{console.error('Agreements workspace failed',err);el('templates-list').textContent='Agreements are unavailable.';});
