const ready = window.reaperAdmin
  ? Promise.resolve(window.reaperAdmin)
  : new Promise((resolve) => document.addEventListener('reaper:admin-ready', (event) => resolve(event.detail), { once: true }));
let context, clients=[], cases=[], reports=[];
const el=(id)=>document.getElementById(id);
const fmt=(v)=>v?new Date(v).toLocaleString():'—';
const money=(v)=>v===null||v===undefined?'—':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(v));
function options(select, rows, label, first='Select') { select.innerHTML=`<option value="">${first}</option>`; for(const row of rows){const o=document.createElement('option');o.value=row.id;o.textContent=label(row);select.appendChild(o);} }
function casesFor(clientId){return cases.filter((c)=>c.client_id===clientId && ['credit repair','credit audit'].includes(String(c.case_type).toLowerCase()));}
function wireClientCase(clientId,caseId){el(clientId).addEventListener('change',()=>options(el(caseId),casesFor(el(clientId).value),(c)=>c.title||c.case_type,'Select credit case'));}
function table(container, headers, rows){container.replaceChildren();if(!rows.length){container.textContent='No records yet.';return;}const t=document.createElement('table');t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${h.label}</th>`).join('')}</tr></thead>`;const b=document.createElement('tbody');for(const row of rows){const tr=document.createElement('tr');for(const h of headers){const td=document.createElement('td');const v=h.render?h.render(row):row[h.key];if(v instanceof Node)td.appendChild(v);else td.textContent=v??'—';tr.appendChild(td);}b.appendChild(tr);}t.appendChild(b);container.appendChild(t);}
async function loadRefs(){const {supabase}=context;const [cr,ca,rr]=await Promise.all([supabase.from('clients').select('id,full_name,email').order('full_name'),supabase.from('cases').select('id,client_id,case_type,title,status').order('created_at',{ascending:false}),supabase.from('credit_reports').select('id,client_id,case_id,report_date,source,status,created_at').order('created_at',{ascending:false})]);if(cr.error||ca.error||rr.error)throw cr.error||ca.error||rr.error;clients=cr.data||[];cases=ca.data||[];reports=rr.data||[];for(const id of ['report-client','issue-client','round-client'])options(el(id),clients,(c)=>`${c.full_name||c.email} (${c.email})`);options(el('tradeline-report'),reports,(r)=>`${clients.find(c=>c.id===r.client_id)?.full_name||'Client'} · ${r.report_date||'undated'} · ${r.source||'report'}`,'Select report');}
async function loadLists(){const {supabase}=context;const [rr,ir,dr]=await Promise.all([supabase.from('credit_reports').select('id,client_id,case_id,report_date,source,status,created_at').order('created_at',{ascending:false}),supabase.from('credit_issues').select('id,client_id,case_id,bureau,issue_code,issue_type,severity,status,created_at').order('created_at',{ascending:false}),supabase.from('dispute_rounds').select('id,client_id,case_id,round_number,target_type,target_name,bureau,status,sent_at,response_due_at,created_at').order('created_at',{ascending:false})]);reports=rr.data||[];table(el('reports-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Date',key:'report_date'},{label:'Source',key:'source'},{label:'Status',key:'status'},{label:'Created',render:r=>fmt(r.created_at)}],reports);table(el('issues-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Bureau',key:'bureau'},{label:'Code',key:'issue_code'},{label:'Issue',key:'issue_type'},{label:'Severity',key:'severity'},{label:'Status',key:'status'}],ir.data||[]);table(el('rounds-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Round',key:'round_number'},{label:'Target',render:r=>`${r.target_type}: ${r.target_name}`},{label:'Bureau',key:'bureau'},{label:'Status',key:'status'},{label:'Sent',render:r=>fmt(r.sent_at)}],dr.data||[]);options(el('tradeline-report'),reports,(r)=>`${clients.find(c=>c.id===r.client_id)?.full_name||'Client'} · ${r.report_date||'undated'} · ${r.source||'report'}`,'Select report');}
wireClientCase('report-client','report-case');wireClientCase('issue-client','issue-case');wireClientCase('round-client','round-case');
el('report-form').addEventListener('submit',async(e)=>{e.preventDefault();const {supabase,profile}=context;const {error}=await supabase.from('credit_reports').insert({client_id:el('report-client').value,case_id:el('report-case').value,report_date:el('report-date').value||null,source:el('report-source').value.trim()||null,created_by:profile.id});el('report-status').textContent=error?'Report record could not be created.':'Report record created.';if(!error){e.target.reset();await loadLists();}});
el('tradeline-form').addEventListener('submit',async(e)=>{e.preventDefault();const report=reports.find(r=>r.id===el('tradeline-report').value);if(!report)return;const {error}=await context.supabase.from('credit_tradelines').insert({report_id:report.id,client_id:report.client_id,bureau:el('tradeline-bureau').value,furnisher_name:el('tradeline-furnisher').value.trim(),account_reference_masked:el('tradeline-account').value.trim()||null,account_status:el('tradeline-status').value.trim()||null,balance:el('tradeline-balance').value?Number(el('tradeline-balance').value):null});el('tradeline-form-status').textContent=error?'Tradeline could not be added.':'Tradeline added.';if(!error)e.target.reset();});
el('issue-form').addEventListener('submit',async(e)=>{e.preventDefault();const {supabase,profile}=context;const {error}=await supabase.from('credit_issues').insert({client_id:el('issue-client').value,case_id:el('issue-case').value,bureau:el('issue-bureau').value||null,issue_code:el('issue-code').value.trim(),issue_type:el('issue-type').value.trim(),description:el('issue-description').value.trim(),severity:el('issue-severity').value,created_by:profile.id});el('issue-status').textContent=error?'Issue could not be classified.':'Issue classified.';if(!error){e.target.reset();await loadLists();}});
el('round-form').addEventListener('submit',async(e)=>{e.preventDefault();const {error}=await context.supabase.from('dispute_rounds').insert({client_id:el('round-client').value,case_id:el('round-case').value,round_number:Number(el('round-number').value),target_type:el('round-target-type').value,target_name:el('round-target-name').value.trim(),bureau:el('round-bureau').value||null,method:el('round-method').value.trim()||null,status:'draft'});el('round-status').textContent=error?'Draft dispute round could not be created.':'Draft dispute round created for operator review.';if(!error){e.target.reset();el('round-number').value='1';await loadLists();}});
ready.then(async(v)=>{context=v;await loadRefs();await loadLists();}).catch(err=>{console.error('Credit operations load failed',err);el('reports-list').textContent='Credit operations are unavailable.';});
