const ready = window.reaperAdmin
  ? Promise.resolve(window.reaperAdmin)
  : new Promise((resolve) => document.addEventListener('reaper:admin-ready', (event) => resolve(event.detail), { once: true }));
let context,clients=[],cases=[];
const el=(id)=>document.getElementById(id);
const money=(v)=>v===null||v===undefined?'—':new Intl.NumberFormat(undefined,{style:'currency',currency:'USD'}).format(Number(v));
const fmt=(v)=>v?new Date(v).toLocaleDateString():'—';
const lines=(value)=>String(value||'').split('\n').map(s=>s.trim()).filter(Boolean);
function options(select,rows,label,first='Select'){select.innerHTML=`<option value="">${first}</option>`;for(const row of rows){const o=document.createElement('option');o.value=row.id;o.textContent=label(row);select.appendChild(o);}}
function fundingCases(clientId){return cases.filter(c=>c.client_id===clientId && String(c.case_type).toLowerCase().includes('funding'));}
function wire(clientId,caseId){el(clientId).addEventListener('change',()=>options(el(caseId),fundingCases(el(clientId).value),c=>c.title||c.case_type,'Select funding case'));}
function render(container,headers,rows){container.replaceChildren();if(!rows.length){container.textContent='No records yet.';return;}const t=document.createElement('table');t.innerHTML=`<thead><tr>${headers.map(h=>`<th>${h.label}</th>`).join('')}</tr></thead>`;const b=document.createElement('tbody');for(const r of rows){const tr=document.createElement('tr');for(const h of headers){const td=document.createElement('td');td.textContent=(h.render?h.render(r):r[h.key])??'—';tr.appendChild(td);}b.appendChild(tr);}t.appendChild(b);container.appendChild(t);}
async function loadRefs(){const {supabase}=context;const [cl,ca]=await Promise.all([supabase.from('clients').select('id,full_name,email').order('full_name'),supabase.from('cases').select('id,client_id,case_type,title,status').order('created_at',{ascending:false})]);if(cl.error||ca.error)throw cl.error||ca.error;clients=cl.data||[];cases=ca.data||[];for(const id of ['business-client','readiness-client','application-client'])options(el(id),clients,c=>`${c.full_name||c.email} (${c.email})`);}
async function loadLists(){const {supabase}=context;const [ra,ap,lp]=await Promise.all([supabase.from('funding_readiness_assessments').select('id,client_id,case_id,score,status,summary,published_at,created_at').order('created_at',{ascending:false}),supabase.from('funding_applications').select('id,client_id,case_id,lender_name,product_type,amount_requested,amount_approved,status,application_date,created_at').order('created_at',{ascending:false}),supabase.from('lender_programs').select('id,lender_name,program_name,product_type,min_personal_credit,min_time_in_business_months,min_monthly_revenue,max_amount,active,source_checked_at').order('lender_name')]);render(el('readiness-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Score',key:'score'},{label:'Status',key:'status'},{label:'Summary',key:'summary'},{label:'Published',render:r=>fmt(r.published_at)}],ra.data||[]);render(el('applications-list'),[{label:'Client',render:r=>clients.find(c=>c.id===r.client_id)?.full_name||r.client_id},{label:'Lender',key:'lender_name'},{label:'Product',key:'product_type'},{label:'Requested',render:r=>money(r.amount_requested)},{label:'Approved',render:r=>money(r.amount_approved)},{label:'Status',key:'status'}],ap.data||[]);render(el('lenders-list'),[{label:'Lender',key:'lender_name'},{label:'Program',key:'program_name'},{label:'Product',key:'product_type'},{label:'Min credit',key:'min_personal_credit'},{label:'Min monthly revenue',render:r=>money(r.min_monthly_revenue)},{label:'Max amount',render:r=>money(r.max_amount)},{label:'Active',render:r=>r.active?'Yes':'No'}],lp.data||[]);}
wire('readiness-client','readiness-case');wire('application-client','application-case');
el('business-client').addEventListener('change',async()=>{const id=el('business-client').value;if(!id)return;const {data}=await context.supabase.from('business_profiles').select('*').eq('client_id',id).maybeSingle();if(!data)return;el('business-name').value=data.legal_name||'';el('business-entity').value=data.entity_type||'';el('business-state').value=data.formation_state||'';el('business-date').value=data.formation_date||'';el('business-naics').value=data.naics_code||'';el('business-annual').value=data.annual_revenue??'';el('business-monthly').value=data.average_monthly_revenue??'';el('business-months').value=data.time_in_business_months??'';el('business-debt').value=data.existing_business_debt??'';});
el('business-form').addEventListener('submit',async(e)=>{e.preventDefault();const payload={client_id:el('business-client').value,legal_name:el('business-name').value.trim()||null,entity_type:el('business-entity').value.trim()||null,formation_state:el('business-state').value.trim().toUpperCase()||null,formation_date:el('business-date').value||null,naics_code:el('business-naics').value.trim()||null,annual_revenue:el('business-annual').value?Number(el('business-annual').value):null,average_monthly_revenue:el('business-monthly').value?Number(el('business-monthly').value):null,time_in_business_months:el('business-months').value?Number(el('business-months').value):null,existing_business_debt:el('business-debt').value?Number(el('business-debt').value):null,updated_at:new Date().toISOString()};const {error}=await context.supabase.from('business_profiles').upsert(payload,{onConflict:'client_id'});el('business-status').textContent=error?'Business profile could not be saved.':'Business profile saved.';});
el('readiness-form').addEventListener('submit',async(e)=>{e.preventDefault();const state=el('readiness-state').value;const {error}=await context.supabase.from('funding_readiness_assessments').insert({client_id:el('readiness-client').value,case_id:el('readiness-case').value,score:Number(el('readiness-score').value),summary:el('readiness-summary').value.trim()||null,strengths:lines(el('readiness-strengths').value),gaps:lines(el('readiness-gaps').value),status:state,created_by:context.profile.id,published_at:state==='published'?new Date().toISOString():null});el('readiness-status').textContent=error?'Assessment could not be saved.':'Assessment saved.';if(!error){e.target.reset();await loadLists();}});
el('lender-form').addEventListener('submit',async(e)=>{e.preventDefault();const lender=el('lender-name').value.trim(),program=el('lender-program').value.trim();const payload={lender_name:lender,program_name:program,product_type:el('lender-product').value.trim(),min_personal_credit:el('lender-credit').value?Number(el('lender-credit').value):null,min_time_in_business_months:el('lender-months').value?Number(el('lender-months').value):null,min_monthly_revenue:el('lender-revenue').value?Number(el('lender-revenue').value):null,max_amount:el('lender-max').value?Number(el('lender-max').value):null,source_url:el('lender-source').value.trim()||null,source_checked_at:new Date().toISOString(),updated_at:new Date().toISOString()};const {error}=await context.supabase.from('lender_programs').upsert(payload,{onConflict:'lender_name,program_name'});el('lender-status').textContent=error?'Lender program could not be saved.':'Lender program saved.';if(!error){e.target.reset();await loadLists();}});
el('application-form').addEventListener('submit',async(e)=>{e.preventDefault();const {error}=await context.supabase.from('funding_applications').insert({client_id:el('application-client').value,case_id:el('application-case').value,lender_name:el('application-lender').value.trim(),product_type:el('application-product').value.trim()||null,amount_requested:el('application-amount').value?Number(el('application-amount').value):null,status:el('application-status').value,application_date:el('application-date').value||null});el('application-form-status').textContent=error?'Application could not be saved.':'Application saved.';if(!error){e.target.reset();await loadLists();}});
ready.then(async(v)=>{context=v;await loadRefs();await loadLists();}).catch(err=>{console.error('Funding operations load failed',err);el('readiness-list').textContent='Funding operations are unavailable.';});
